import { Suspense } from 'react';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type ReactChildrenProps = {
  children: React.ReactNode;
};
function RootLayout({ children }: ReactChildrenProps) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

interface AppProps {
  children: React.ReactNode;
  invoices: React.ReactNode;
}
function App({ children, invoices }: AppProps) {
  return (
    <RootLayout>
      <Suspense fallback={<div>app loading...</div>}>{children}</Suspense>
    </RootLayout>
  );
}

export default App;
